// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAONsyio48zedar9-bSzhtCHV30BJlVI5M',
    appId: '1:178948988947:web:d6521a6167acc0b2cb5fe6',
    messagingSenderId: '178948988947',
    projectId: 'gestionnaire-d-epicerie',
    authDomain: 'gestionnaire-d-epicerie.firebaseapp.com',
    storageBucket: 'gestionnaire-d-epicerie.appspot.com',
    measurementId: 'G-W90J1GB4WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaOhB2XnKTNTFXsGTWWVsFbroPi6snnY',
    appId: '1:178948988947:android:fe56eed35cd3bbeecb5fe6',
    messagingSenderId: '178948988947',
    projectId: 'gestionnaire-d-epicerie',
    storageBucket: 'gestionnaire-d-epicerie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7cm1fjFUwNXAIdBr70oyJZrrFXrlfvks',
    appId: '1:178948988947:ios:6c79153df87a8391cb5fe6',
    messagingSenderId: '178948988947',
    projectId: 'gestionnaire-d-epicerie',
    storageBucket: 'gestionnaire-d-epicerie.appspot.com',
    iosClientId: '178948988947-bo17orpa8rlu5fod44jm23s7ngbrncig.apps.googleusercontent.com',
    iosBundleId: 'ca.cal.tp4.lpf.listeEpicerie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7cm1fjFUwNXAIdBr70oyJZrrFXrlfvks',
    appId: '1:178948988947:ios:6c79153df87a8391cb5fe6',
    messagingSenderId: '178948988947',
    projectId: 'gestionnaire-d-epicerie',
    storageBucket: 'gestionnaire-d-epicerie.appspot.com',
    iosClientId: '178948988947-bo17orpa8rlu5fod44jm23s7ngbrncig.apps.googleusercontent.com',
    iosBundleId: 'ca.cal.tp4.lpf.listeEpicerie',
  );
}
